kind: ReplicaSet
apiVersion: apps/v1                            
metadata:
  name: myrs
spec:
  replicas: 2
  selector:
    matchExpressions:                             # these must match t
      - {key: myname, operator: In, values: [Bhupinder, Bupinder, Bhopi]}
      - {key: env, operator: NotIn, values: [production]}
  template:
    metadata:
      name: testpod7
      labels:
        myname: Bhupinder
    spec:
     containers:
     - name: c00
       image: ubuntu
       command: ["/bin/bash", "-c", "while true; do echo Hello-yadav; sleep 5; done"]
