kind: Pod
apiVersion: v1 
metadata:
   name: pod-port
spec:
   containers:
     - name: c04
       image: httpd
       ports:
         - containerPort: 80
~                                                                                                                                                
~                                                                                                                                                
~                                                                                                                                                
~                                                                                                                                                
~                                    
