---
- name: This playbook is to create user 
  hosts: localhost      # Target Section 
  user: kavitha
  become: true
  connection: shh

  tasks:                     # Task Section
  - name: Creating user Arohi
    user:
       name: arohi                       # module is user
